name: WorldCommand
main: com.github.vahnatai.worldcommand.WorldCommandPlugin
version: 0.0.1
commands:
   world:
      description: World management command.
      usage: /world (create | unload | delete) worldname [createtype]
      permission: world.world
      permission-message: You do not have permission to use that command.